{{
  config(
    materialized='table'
  )
}}

WITH int_product_views AS (
  SELECT
    *
  FROM {{ ref('int_postgres__product_views') }}
)

SELECT
  SESSION_ID,
  PRODUCT_ID,
  PRODUCT_NAME,
  PRODUCT_PRICE,
  PRODUCT_URL,
  USER_ID,
  USER_FULL_NAME,
  MIN(VIEW_DATE) AS VIEW_DATE,
  COUNT(PRODUCT_ID) AS NUM_VIEWS,
  SUM(CASE WHEN ADD_TO_CART_DATE IS NOT NULL THEN 1 ELSE 0 END) AS NUM_ADDED_TO_CART,
  SUM(CASE WHEN CHECKOUT_DATE IS NOT NULL THEN 1 ELSE 0 END) AS NUM_CHECKOUT,
  SUM(CASE WHEN SHIP_DATE IS NOT NULL THEN 1 ELSE 0 END) AS NUM_SHIPPED
FROM int_product_views
GROUP BY 1,2,3,4,5,6,7