{{
  config(
    materialized='table'
  )
}}

WITH int_product_views AS (
  SELECT
    *
  FROM {{ ref('int_postgres__product_views') }}
)

SELECT
  VIEW_ID,
  SESSION_ID,
  PRODUCT_ID,
  PRODUCT_NAME,
  PRODUCT_PRICE,
  PRODUCT_URL,
  USER_ID,
  USER_FULL_NAME,
  VIEW_DATE,
  ADD_TO_CART_DATE,
  CHECKOUT_DATE,
  SHIP_DATE,
  CASE WHEN ADD_TO_CART_DATE IS NOT NULL THEN TRUE ELSE FALSE END AS IS_ADDED_TO_CART,
  CASE WHEN CHECKOUT_DATE IS NOT NULL THEN TRUE ELSE FALSE END AS IS_CHECKED_OUT,
  CASE WHEN SHIP_DATE IS NOT NULL THEN TRUE ELSE FALSE END AS IS_SHIPPED
FROM int_product_views