WITH fact_orders AS (
  SELECT
    *
  FROM {{ source('fact_postgres', 'fact_postgres__orders') }}
)

SELECT
    ORDER_ID,
    ROUND(SUM(ORDER_COST + SHIPPING_COST) - SUM(PROMO_DISCOUNT), 2) AS ORDER_TOTAL_CALC,
    ROUND(SUM(ORDER_TOTAL), 2) AS ORDER_TOTAL_ACTUAL
FROM fact_orders
GROUP BY 1
HAVING NOT (ORDER_TOTAL_CALC = ORDER_TOTAL_ACTUAL)